x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION:-0}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped
    logging: *default-logging

  etl:
    build:
      context: .
      dockerfile: images/Dockerfile.etl
    image: poview-etl:1.0
    container_name: etl
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      ETL_CRON: ${ETL_CRON:-0 4 * * *}
      RUN_ON_START: ${RUN_ON_START:-1}
    restart: unless-stopped
    logging: *default-logging

  ollama:
      image: ollama/ollama:latest
      container_name: ollama
      ports:
        - "11434:11434"
      environment:
            OLLAMA_KEEP_ALIVE: "30m"
      volumes:
        - ollama-data:/root/.ollama
      restart: unless-stopped
      logging: *default-logging

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      OLLAMA_URL: http://ollama:11434 
      OLLAMA_MODEL: ${OLLAMA_MODEL:-qwen3:8b}
    depends_on:
      - influxdb
      - ollama
    restart: unless-stopped
    logging: *default-logging


  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: poblacion-app
    ports:
      - "8080:3000"
    environment:
      VITE_BACKEND: http://backend:8000
      VITE_API_URL: /api
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging: *default-logging

volumes:
  influxdb-data:
  influxdb-config:
  ollama-data: